/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.hngc.chat2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.hngc.chat2.models.query.*;

@Service
public class Chat2QueryExecutorServiceImpl implements Chat2QueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Chat2QueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("chat2WMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "chat2TransactionManager", readOnly = true)
    @Override
    public Page<OwnpicResponse> executeOwnpic(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("ownpic", params, OwnpicResponse.class, pageable);
    }

    @Transactional(value = "chat2TransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportOwnpic(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput<OwnpicResponse> queryInput = new QueryProcedureInput<>("ownpic", params, OwnpicResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}