/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.hngc.chat2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.hngc.chat2.models.query.*;

public interface Chat2QueryExecutorService {

    Page<OwnpicResponse> executeOwnpic(Pageable pageable);

    void exportOwnpic(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}