/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.hngc.chat2.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class OwnpicResponse implements Serializable {


    @ColumnAlias("pic")
    private String pic;

    public String getPic() {
        return this.pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof OwnpicResponse)) return false;
        final OwnpicResponse ownpicResponse = (OwnpicResponse) o;
        return Objects.equals(getPic(), ownpicResponse.getPic());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPic());
    }
}